### ISSUE TITLE
Add RocketChat/developer-docs to included repositories

### ISSUE THREAD

**Issue by ahmedibrahim404** [RocketChat/Opensource-Contribution-Leaderboard#100]
## Description:
I think  [developer-docs](https://github.com/RocketChat/developer-docs) repository should be added to included repositories `config.json` located at `/src/server`

**Comment by ahmedibrahim404** [comment]
Hi @Sing-Li ,

Could you please check this?

**Comment by Sing-Li** [comment]
Agreed.   @ahmedibrahim404 !   Thanks for the heads-up.

**Comment by Sing-Li** [comment]
Should be included now.  Please reopen if not.
