### ISSUE TITLE
Making a new contributors experience 



### ISSUE THREAD

**Issue by shubham21155102** [RocketChat/Opensource-Contribution-Leaderboard#105]
I just want to design this repo in a new way
•Making Responsive
•Designing UI
•Will Add Theming Kit
•Layout Modification
•Custom Handling of Avtar and username 
•Will Add responsiveness 
•will improve performance
•will add a section to faster setting up for repos to the contributors
•will work on Typescript format

**Comment by shubham21155102** [comment]
Please assign me for such

**Comment by Sing-Li** [comment]
Thanks for your ideas @shubham21155102   But we really have no need for any of it at this time.   This issue will be closed.
