### ISSUE TITLE
[BUG] Sorting is not working

### ISSUE THREAD

**Issue by shubhsherl** [RocketChat/Opensource-Contribution-Leaderboard#3]
Click on the heading of the column. It should sort the board.

**Comment by lolimay** [comment]
> Click on the heading of the column. It should sort the board.

Hi, it actually is a not implemented feature. Please feel free to pull a request :)

**Comment by jugshaurya** [comment]
I would like to do this. can i ? and also @lolimay are you one of the mentor in RocketChat under GSOC?

**Comment by lolimay** [comment]
> I would like to do this. can i ? and also @lolimay are you one of the mentor in RocketChat under GSOC?

Great! Go ahead please! 

> @lolimay are you one of the mentor in RocketChat under GSOC?
Not yet 😜

**Comment by im-adithya** [comment]
@lolimay I am interested in doing this can you help me on how to get started?

**Comment by im-adithya** [comment]
@Sing-Li @lolimay Can you please review my PR? 
Thank you!
