### ISSUE TITLE
[Feature improvement]  Add repositories inclusion/exclusion list

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Opensource-Contribution-Leaderboard#44]
Many Github organizations, such as Rocket.Chat, have a very large number of public repositories.   

Typically, not all public repositories under an organization  should be eligible (counted) in the leaderboard.

Add an inclusion/exclusion list to specify the repositories that should be combed for leaderboard statistics.

**Comment by RonLek** [comment]
@Sing-Li Can I take this up? :)
