### ISSUE TITLE
[Feature request]  Add admin-view-only hidden text ranking

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Opensource-Contribution-Leaderboard#46]
Once the number of participants exceeds one screen page, it becomes more difficult for administrators to track ranking.

We do not want to disturb the simplistic layout of the current  leadboard  to add this field (of interest to admin only).

Add ranking as a hidden text addition to the existing username field.

**Comment by djcruz93** [comment]
I am claiming this issue.
