### ISSUE TITLE
[Bug]  Make "0"  count link non-clickable

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Opensource-Contribution-Leaderboard#59]
With the new query, that can be viewed via users not logged it, clicking on 0-link gives error.

![image](https://user-images.githubusercontent.com/122633/104276152-28e74600-5459-11eb-89db-8533ca418ceb.png)

Best to make zero-links  non-clickable.

**Comment by djcruz93** [comment]
I'll do this.
