### ISSUE TITLE
Links open in current tab.

### ISSUE THREAD

**Issue by kishanhitk** [RocketChat/Opensource-Contribution-Leaderboard#72]
### Description:

Clicking on any link like username or issues count opens the GitHub page in the same tab which can disturb the visitor.

### Steps to reproduce:

1.  Goto Leaderboard page
2. Click on any members' username
3. Their GitHub profile open in same tab

### Expected behavior:

Links should open in new tab.

### Actual behavior:

Links are opening in same tab.

**Comment by Sing-Li** [comment]
It is by design.  Not to clutter users' browser with extra tabs.
