### ISSUE TITLE
Total count is not visible

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Opensource-Contribution-Leaderboard#74]
The total count on the front page is colored white and due to that, it is not visible. 
![total count](https://user-images.githubusercontent.com/54025079/111427541-45835100-871c-11eb-9e92-47e3c74c8f43.JPG)

**Comment by RonLek** [comment]
@ak2783934 it's a feature, not a bug ;)

Take a look [here](https://github.com/RocketChat/Opensource-Contribution-Leaderboard/issues/68)

**Comment by ak2783934** [comment]
Ohh okay, didn't see that. Thanks
