### ISSUE TITLE
Not showing for some users

### ISSUE THREAD

**Issue by sumukhah** [RocketChat/Opensource-Contribution-Leaderboard#76]
Leader board is not showing my name (sumukhah). I have 7-8 open pull requests, 3-4 merged PRs. But still its not showing my name.!!
[My Open Pr's](https://github.com/search?q=type%3Apr+author%3Asumukhah+is%3Aopen+created%3A%3E%3D2020-11-20+repo%3ARocketChat%2FRocket.Chat+repo%3ARocketChat%2FRocket.Chat.Electron+repo%3ARocketChat%2Fdocs+repo%3ARocketChat%2FRocket.Chat.ReactNative+repo%3ARocketChat%2FRocket.Chat.js.SDK+repo%3ARocketChat%2FRocket.Chat.py.SDK+repo%3ARocketChat%2FRocket.Chat.Livechat+repo%3ARocketChat%2FRocket.Chat.Embedded.arm64+repo%3ARocketChat%2FRocket.Chat.Embedded.armhf+repo%3ARocketChat%2Falexa-rocketchat+repo%3ARocketChat%2FOpensource-Contribution-Leaderboard+repo%3ARocketChat%2FRocket.Chat.Fuselage+repo%3ARocketChat%2Falexa-rocketchat-notification+repo%3ARocketChat%2Falexa-rocketchat-flashbriefing+repo%3ARocketChat%2Falexa-news-publisher+repo%3ARocketChat%2Falexa-rc-multiserver-client+repo%3ARocketChat%2FApps.Rasa+repo%3ARocketChat%2FApps.Dialogflow)
[Merged Pr's](https://github.com/search?q=type%3Apr+author%3Asumukhah+is%3Aopen+created%3A%3E%3D2020-11-20+repo%3ARocketChat%2FRocket.Chat+repo%3ARocketChat%2FRocket.Chat.Electron+repo%3ARocketChat%2Fdocs+repo%3ARocketChat%2FRocket.Chat.ReactNative+repo%3ARocketChat%2FRocket.Chat.js.SDK+repo%3ARocketChat%2FRocket.Chat.py.SDK+repo%3ARocketChat%2FRocket.Chat.Livechat+repo%3ARocketChat%2FRocket.Chat.Embedded.arm64+repo%3ARocketChat%2FRocket.Chat.Embedded.armhf+repo%3ARocketChat%2Falexa-rocketchat+repo%3ARocketChat%2FOpensource-Contribution-Leaderboard+repo%3ARocketChat%2FRocket.Chat.Fuselage+repo%3ARocketChat%2Falexa-rocketchat-notification+repo%3ARocketChat%2Falexa-rocketchat-flashbriefing+repo%3ARocketChat%2Falexa-news-publisher+repo%3ARocketChat%2Falexa-rc-multiserver-client+repo%3ARocketChat%2FApps.Rasa+repo%3ARocketChat%2FApps.Dialogflow&state=closed&type=Issues)

**Comment by RonLek** [comment]
@sumukhah you need to post a message in the GSoC channel on the https://open.rocket.chat server with your GitHub username. The addition to the leaderboard is not automated and is manually done to avoid spamming. This is not an issue with the app. (Find the channel for GSoC 2021 [here](https://open.rocket.chat/channel/gsoc2021))

Please close this issue if your query was resolved.

**Comment by sumukhah** [comment]
@RonLek , Thanks, I think it would solve this issue.
I have messaged in the channel yesterday. It has not updated yet. How much time would it take to update?

**Comment by RonLek** [comment]
@sumukhah I've continued our [conversation](https://open.rocket.chat/channel/gsoc2021?msg=goxZvAt9anGkRAJT2) in the channel. Thanks.

**Comment by sumukhah** [comment]
Oh.. I didn't know students should be added manually. I thought it will be done by some kind of bots,..That's why I just texted "Hello" (My bad ).. Sorry for that
