### ISSUE TITLE
Leaderboard ranking is Hidden

### ISSUE THREAD

**Issue by umakantv** [RocketChat/Opensource-Contribution-Leaderboard#79]
Is this intentional?
| Hidden Text | Showing on selection |
| - | - |
| ![image](https://user-images.githubusercontent.com/41837826/114912116-40114780-9e3d-11eb-8ef8-5195566729a2.png) | ![image](https://user-images.githubusercontent.com/41837826/114912256-6a630500-9e3d-11eb-88eb-ffc9c23d57f3.png) |

**Comment by RonLek** [comment]
@umakantv yes. Please take a look at similar closed issues.

**Comment by umakantv** [comment]
@RonLek okay.
