### ISSUE TITLE
[Feature Request] Display All New Contributors / GSOC contributors currently opened issues and PR's. (More in Comment)

### ISSUE THREAD

**Issue by Udit-takkar** [RocketChat/Opensource-Contribution-Leaderboard#91]
Unresponsive maintainers become a bottleneck for open source projects. If someone submits a contribution but never hears back from a maintainer, they may feel discouraged and leave.

Research from Mozilla suggests that maintainer responsiveness is a critical factor in encouraging repeat contributions.

Consider tracking how long it takes for you (or another maintainer) to respond to contributions, whether an issue or a pull request. Responding doesn’t require taking action. It can be as simple as saying: “Thanks for your submission! I’ll review this within the next week.”

You could also measure the time it takes to move between stages in the contribution process, such as:

Average time an issue remains open
Whether issues get closed by PRs
Whether stale issues get closed
Average time to merge a pull request

As there are more 2.5k issues open out of which a lot of them are not replied back or stale or duplicate. It is very difficult to filter through relevant issues.
We could have all the new contributors who want to learn/contribute username here and then display all the open issues raised by them and PR's in progress.  as Open source is about **Collaboration**  other new contributors can collaboratively resolve issues and help each other if they are unable to go forward with a PR and help solve blockers or suggest them some other issues. 

As Open Source is positive sum game, we all could build new features together and fix bugs.

**Comment by Udit-takkar** [comment]
@Sing-Li @yash-rajpal

**Comment by Udit-takkar** [comment]
I'll build this feature

**Comment by Sing-Li** [comment]
@Udit-takkar   tracking general open source metrics is not the purpose of this leaderboard project.   Closing.
