### ISSUE TITLE
[IMPROVE] Need better sorting buttons

### ISSUE THREAD

**Issue by aswinidev** [RocketChat/Opensource-Contribution-Leaderboard#92]
I visited https://gsoc.rocket.chat/ and clicked on this button randomly
![Screenshot from 2021-12-30 20-41-56](https://user-images.githubusercontent.com/76481696/147764005-df0885de-db07-45cb-9d27-bd84463402fc.png)
Then I got to know that these buttons are for sorting the list in various ways. I think it could have been implemented better by may be adding some buttons so that people would understand what it could do. As of now the sorting feature seems hidden.

**Comment by Sing-Li** [comment]
We do not need cosmetics improvement in this project.   Closing the issue.
