### ISSUE TITLE
[BUG] Some content are invisible in the dashboard

### ISSUE THREAD

**Issue by nipunayf** [RocketChat/Opensource-Contribution-Leaderboard#98]
**Actual behavior:**
The following content are not visible in the dashboard.
1. Total contributors.
2. The rank of each contributor.
3. Total merged PRs, open PRs, and issues.

![Screenshot from 2022-03-20 23-13-59](https://user-images.githubusercontent.com/59343084/159178574-21dc7e83-31da-4a56-9a58-78ea57674cdd.png)

**Expected behavior:**
The considered fields must be visible in the dashboard.

**Browser version:**
Google Chrome - Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by RonLek** [comment]
@nipunayf this is not a bug. See similar closed issues (#79 #74 #69). Quoting from a previous issue
> Please try to talk us and confirm before spending the energy on bug fixes next time.

**Comment by nipunayf** [comment]
Thank you for the references and I apologize for not checking the closed issues earlier :sweat_smile:. However, I have one last thing to confirm. If someone enforces a dark reader plugin or uses the dark theme in the Google Chrome mobile app, then these become visible again. I assume this is a part of the implementation as well? :thinking: 
<img src="https://user-images.githubusercontent.com/59343084/159211772-dea1f55c-05c6-485c-aedb-1fa9de9afa78.jpg" width=400/>

**Comment by RonLek** [comment]
@nipunayf that's strange. [Here's](https://ibb.co/k39LHb3) what I get with Chrome dark mode turned on. Ideally, I believe browser color mode shouldn't impact the color-scheme of websites (instead should only do so for browser components). 

In case of users with a special plugin, I believe the onus of accurate mode-conversion falls onto the plugin itself (for creating dark mode where none exists). Until **we** decide to add dark mode to the leaderboard in the future, I'm of the opinion displaying this should do no harm to the very small number of users with this plugin (no sensitive information involved).

**Comment by nipunayf** [comment]
That makes sense. Thank you for the information.
